**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# Import pandas
import pandas as pd

# Q1-1
myFrame = pd.DataFrame(data)
# Q1-2
myFrame[((myFrame["job"] == "teacher") | (myFrame["job"] == "psychologist")) & (myFrame["family_size"] < myFrame["num_cars"])]
# Q1-3
myFrame[(myFrame["family_size"] <= 2) & (myFrame["num_cars"]) >= 1]
# Q1-4
len(pd.unique(myFrame["job"]))

4

**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
# Construct the corresponding dataframe
myFrame = pd.DataFrame(columns = ["fruit", "weights"])
myFrame["fruit"] = fruit
myFrame["weights"] = weights

# Calculating and Printing -- remember to address the 0 cases
print("Apples' average weight is ", end = '')
if np.sum(myFrame[myFrame["fruit"] == "apple"].weights):
  print(str(np.mean(myFrame[myFrame["fruit"] == "apple"].weights)))
else:
  print(0)

print("Bananas' average weight is ", end = '')
if np.sum(myFrame[myFrame["fruit"] == "banana"].weights):
  print(str(np.mean(myFrame[myFrame["fruit"] == "banana"].weights)))
else:
  print(0)

print("Carrots' average weight is ", end = '')
if np.sum(myFrame[myFrame["fruit"] == "carrot"].weights):
  print(str(np.mean(myFrame[myFrame["fruit"] == "carrot"].weights)))
else:
  print(0)

Apples' average weight is 5.0
Bananas' average weight is 6.666666666666667
Carrots' average weight is 5.0


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Q3-1
print(np.where(np.sort(course_name)))
print(np.sort(course_name)[np.where(np.sort(course_name))])

# Q3-2
ifStartWithLetterP = np.char.startswith(course_name, 'P')
print(len(ifStartWithLetterP[ifStartWithLetterP == True]) == len(course_name))

(array([0, 1, 2, 3, 4]),)
['JS' 'PHP' 'Python' 'examples' 'html']
False


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
# Q4-1
reversed_student_id = np.flip(student_id, 0)
print(student_id)
print(reversed_student_id)

# Q4-2
sorted_student_id = np.sort(student_id)
print("The largest element of the student_id array is " +  str(sorted_student_id[-1]))
print("The second largest element of the student_id array is " + str(sorted_student_id[-2]))
print("The third largest element of the student_id array is " + str(sorted_student_id[-3]))

[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]
The largest element of the student_id array is 6230
The second largest element of the student_id array is 5241
The third largest element of the student_id array is 5202


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
nArray = np.arange(1, 100)
print("The sum of all the multiples of 3 or 5 below 100 is " + str(np.sum(nArray[(nArray % 3 == 0) | (nArray % 5 == 0)])))

The sum of all the multiples of 3 or 5 below 100 is 2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Q6.1
arr1 = arr[:, [0, 2, 1, 3]]
print(arr1)

print()

# Q6.2
arr2 = arr[[1, 0, 2], :]
print(arr2)